
path=(
#default
/usr/local/sbin
/usr/local/bin
/usr/bin
/usr/bin/core_perl
#forMac
/opt/local/bin
/opt/local/sbin
/bin
/sbin
/Users/masa/bin
#rubygems
~/.gem/ruby/2.1.0/bin
)

typeset -U path

vimruntime=(
/usr/share/vim/vim74/
)

library_path=(
/opt/local/lib
)

ld_library_path=(
/opt/local/lib
)

c_include_path=(
/opt/local/include
)

cplus_include_path=(
/opt/local/include
)

dyld_fallback_library_path=(
/opt/local/lib
)

boost_root=(
/opt/local/include/boost
)
