
export EDITOR=vim
export LANG=ja_JP.UTF-8

#plugin managed by zplug
export ZPLUG_HOME=~/.zplug/
source $ZPLUG_HOME/zplug/init.zsh


bindkey -v

setopt auto_cd
setopt correct
setopt auto_pushd
setopt cdable_vars
setopt extended_glob

export CLICOLOR=true
autoload -U colors
colors

autoload -U compinit promptinit
promptinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' list-colors '${LS_COLORS}'

PROMPT="%n %c%# "
RPROMPT="%D%t"

autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end

#keybind
bindkey '^P' history-beginning-search-backward-end
bindkey '^N' history-beginning-search-forward-end
bindkey -M vicmd 'q' push-line
bindkey '' cdup
bindkey -M vicmd '\@' start_editor
bindkey -M viins '^F' forward-char
bindkey -M viins '^B' backward-char

#alias
alias la="ls -a"
alias llh="ls -lh"

#historys
HISTSIZE=20000
SAVEHIST=10000
HISTFILE=~/.zsh_history

#functions

##cd up
function cdup() {
    echo
    cd ..
    pwd
    zle reset-prompt
}
zle -N cdup

##start editor on current dir
function start_editor() {
    exec < /dev/tty
    ${EDITOR}
    zle reset-prompt
}
zle -N start_editor

#ocaml
. /Users/masa/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
