
export EDITOR=vim
export LANG=ja_JP.UTF-8

bindkey -v

setopt auto_cd
setopt correct
setopt auto_pushd
setopt cdable_vars
setopt extended_glob

export CLICOLOR=true
autoload -U colors
colors

autoload -U compinit promptinit
promptinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' list-colors '${LS_COLORS}'

PROMPT="%n %c%# "
RPROMPT="%D%t"

autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end

#keybind
bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end
bindkey -a "q" push-line
bindkey '' cdup
bindkey '\@' start_editor

#alias
alias lc="ls --color"
alias la="ls -a"
alias llh="ls -lh"
alias hist="history"
alias -g V="2>&1 | vim - -R"

#historys
HISTSIZE=20000
SAVEHIST=10000
HISTFILE=~/.zsh_history

#functions

##cd up
function cdup() {
    echo
    cd ..
    pwd
    zle reset-prompt
}
zle -N cdup

##start editor on current dir
function start_editor() {
    exec < /dev/tty
    ${EDITOR}
    zle reset-prompt
}
zle -N start_editor

#ocaml
eval `opam config env`

